### ISSUE TITLE
Some sites always redirect back to http://

### ISSUE THREAD

**Issue by Kubuxu** [lidel/ipfs-firefox-addon#87]
Example: fs:/ipns/glowing-bear.ipfs.ovh/

**Comment by lidel** [comment]
I assume we are talking about "native" `fs:` mode.
To clarify, does it happen only when local gateway is used?

**Comment by Kubuxu** [comment]
Yes it does.

Also in this case using `fs:/` breaks angular. I will open new issue about maybe meta tag for requesting for not  being under `fs:/`.

**Comment by lidel** [comment]
Ok, it seems that relative links also escape from `fs:`

Quick repro:

- open `fs:/ipns/ipfs.io/` and hover over "Examples" link.     
    Note that
   `<a href="./docs/examples">Examples</a>`     
    points to `fs:/ipns/ipfs.io/docs/examples`
- click on it
- `http://127.0.0.1:8080/ipns/ipfs.io/docs/examples/` is loaded

**Comment by lidel** [comment]
There is an upstream ticket about this behavior at https://github.com/ipfs/in-web-browsers/issues/8

**Comment by lidel** [comment]
Closing as it is no longer relevant.

Sadly "native fs: mode" is no longer possible due to missing WebExtension API.
Until such API is created, only basic handler will be present and it will always default to "http" in address bar.

See https://github.com/lidel/ipfs-firefox-addon/issues/164 for more details
